export const BUSINESS_CATEGORIES = [
    "Accountants",
    "Advertising Agencies",
    "Architects",
    "Auto Repair Shops",
    "Bakeries",
    "Banks",
    "Barbers",
    "Bars",
    "Beauty Salons",
    "Bookstores",
    "Breweries",
    "Builders",
    "Cafes",
    "Car Dealerships",
    "Carpenters",
    "Caterers",
    "Child Care Services",
    "Chiropractors",
    "Cleaning Services",
    "Clothing Stores",
    "Coffee Shops",
    "Computer Repair",
    "Consultants",
    "Contractors",
    "Convenience Stores",
    "Day Spas",
    "Dentists",
    "Doctors",
    "Dry Cleaners",
    "Electricians",
    "Electronics Stores",
    "Event Planners",
    "Financial Advisors",
    "Fitness Centers",
    "Florists",
    "Funeral Homes",
    "Furniture Stores",
    "Gas Stations",
    "General Contractors",
    "Gift Shops",
    "Graphic Designers",
    "Grocery Stores",
    "Gyms",
    "Hair Salons",
    "Hardware Stores",
    "Home Inspectors",
    "Hotels",
    "HVAC Services",
    "Insurance Agents",
    "Interior Designers",
    "IT Services",
    "Jewelry Stores",
    "Landscapers",
    "Lawyers",
    "Libraries",
    "Locksmiths",
    "Marketing Agencies",
    "Massage Therapists",
    "Mechanics",
    "Medical Clinics",
    "Movers",
    "Music Schools",
    "Nail Salons",
    "Notaries",
    "Optometrists",
    "Painters",
    "Pet Groomers",
    "Pet Stores",
    "Pharmacies",
    "Photographers",
    "Physical Therapists",
    "Pizza Places",
    "Plumbers",
    "Printing Services",
    "Real Estate Agents",
    "Restaurants",
    "Retail Stores",
    "Roofers",
    "Schools",
    "Security Systems",
    "Shoe Stores",
    "Software Companies",
    "Spas",
    "Storage Facilities",
    "Supermarkets",
    "Tailors",
    "Tattoo Parlors",
    "Tax Preparation",
    "Taxi Services",
    "Travel Agencies",
    "Tutoring Services",
    "Veterinarians",
    "Web Designers",
    "Wedding Planners",
    "Yoga Studios"
];
